# Generated by Django 3.1.5 on 2021-11-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True)),
                ('poster', models.ImageField(upload_to='movie/images')),
                ('cast', models.ManyToManyField(to='pinterest.Cast')),
                ('categories', models.ManyToManyField(to='pinterest.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True)),
                ('poster', models.ImageField(upload_to='movie/images')),
                ('cast', models.ManyToManyField(to='pinterest.Cast')),
                ('categories', models.ManyToManyField(to='pinterest.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
