# Generated by Django 3.1.5 on 2021-11-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'verbose_name_plural': 'Cast'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.RenameField(
            model_name='cast',
            old_name='names',
            new_name='name',
        ),
    ]
