# Generated by Django 3.1.5 on 2021-11-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0002_auto_20211112_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, to='pinterest.Cast'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(blank=True, to='pinterest.Category'),
        ),
        migrations.AlterField(
            model_name='series',
            name='cast',
            field=models.ManyToManyField(blank=True, to='pinterest.Cast'),
        ),
        migrations.AlterField(
            model_name='series',
            name='categories',
            field=models.ManyToManyField(blank=True, to='pinterest.Category'),
        ),
    ]
